spring:
  application:
    name: fornecedor
  datasource:
#    driver-class-name:
    password: ";jnf*&y87KJFH"
    username: "fornecedor"
    url: "jdbc:mysql://localhost:3306/fornecedor"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
